server:
  port: 20000

spring:
  application:
    name: opcua
  datasource:
    name: test
    url: jdbc:mysql://117.72.38.236:3306/iot?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&failOverReadOnly=false

    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 117.72.38.236
    port: 6379
    timeout: 20000
    password:
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 10
        max-wait: -1ms
  cache:
    redis:
      use-key-prefix: true
      key-prefix: dev
      cache-null-values: false
      time-to-live: 20s

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

opcua:
  #kepware
#  endpoint-url: opc.tcp://192.168.56.102:49320
  # simulation
  endpoint-url: opc.tcp://192.168.56.102:53530/OPCUA/SimulationServer

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


